require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/company_verifications", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # CompanyVerification. As you add validations to CompanyVerification, be sure to
  # adjust the attributes here as well.

  let(:user1) {
    User.create!(email: "john.smith@tamu.edu",
                 first_name: "John",
                 last_name: "Smith",
                 password: "12346789")
  }

  let(:user2) {
    User.create!(email: "alice.yi@tamu.edu",
                 first_name: "Alice",
                 last_name: "Yi",
                 password: "12346789")
  }

  let(:user3) {
    User.create!(email: "shawn.han@tamu.com",
                 first_name: "Shawn",
                 last_name: "Han",
                 password: "123456789")
  }

  let(:verification1) {
    CompanyVerification.create!(
      user_id: user1.id,
      company_email: "john.smith@company.com",
      company_name:  "Example Company",
    )
  }

  let(:verification2) {
    CompanyVerification.create!(
      user_id: user2.id,
      company_email: "alice.yi@company.com",
      company_name:  "Example Company",
    )
  }

  describe "GET /show" do
    it "renders a successful response" do
      get company_verification_url(verification1)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_company_verification_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      get edit_company_verification_url(verification1)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CompanyVerification and redirects to show page" do
        session[:user_id] = user3.id
        expect {
          post company_verifications_url, params: { company_email: "shawn.han@example.com", company_name: "Example Company"  }
        }.to change(CompanyVerification, :count).by(1)
        expect(response).to redirect_to(company_verification_url(CompanyVerification.last))
      end

      it "creates a new token that is not a repeat" do
        session[:user_id] = user3.id
        company_verification = CompanyVerification.find_by(user_id: session[:user_id])
        expect(company_verification.unique?(verification_token: company_verification.verification_token)).to eq(true)
      end
    end

    context "with invalid parameters" do
      it "does not create a new CompanyVerification" do
        expect {
          post company_verifications_url, params: { company_verification: invalid_attributes }
        }.to change(CompanyVerification, :count).by(0)
      end
    end
  end
end
