require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/company_verifications", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # CompanyVerification. As you add validations to CompanyVerification, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CompanyVerification.create! valid_attributes
      get company_verifications_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      company_verification = CompanyVerification.create! valid_attributes
      get company_verification_url(company_verification)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_company_verification_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      company_verification = CompanyVerification.create! valid_attributes
      get edit_company_verification_url(company_verification)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CompanyVerification" do
        expect {
          post company_verifications_url, params: { company_verification: valid_attributes }
        }.to change(CompanyVerification, :count).by(1)
      end

      it "redirects to the created company_verification" do
        post company_verifications_url, params: { company_verification: valid_attributes }
        expect(response).to redirect_to(company_verification_url(CompanyVerification.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CompanyVerification" do
        expect {
          post company_verifications_url, params: { company_verification: invalid_attributes }
        }.to change(CompanyVerification, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post company_verifications_url, params: { company_verification: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested company_verification" do
        company_verification = CompanyVerification.create! valid_attributes
        patch company_verification_url(company_verification), params: { company_verification: new_attributes }
        company_verification.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the company_verification" do
        company_verification = CompanyVerification.create! valid_attributes
        patch company_verification_url(company_verification), params: { company_verification: new_attributes }
        company_verification.reload
        expect(response).to redirect_to(company_verification_url(company_verification))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        company_verification = CompanyVerification.create! valid_attributes
        patch company_verification_url(company_verification), params: { company_verification: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested company_verification" do
      company_verification = CompanyVerification.create! valid_attributes
      expect {
        delete company_verification_url(company_verification)
      }.to change(CompanyVerification, :count).by(-1)
    end

    it "redirects to the company_verifications list" do
      company_verification = CompanyVerification.create! valid_attributes
      delete company_verification_url(company_verification)
      expect(response).to redirect_to(company_verifications_url)
    end
  end
end
